// <auto-generated />
using System;
using Invoicing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Invoicing.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905111249_ExpandSeedData")]
    partial class ExpandSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Invoicing.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Budapest, Fő u. 1.",
                            Country = "Hungary",
                            Name = "ABC Ltd"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Debrecen, Piac u. 12.",
                            Country = "Hungary",
                            Name = "Tech Solutions Kft"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Oslo, Karl Johans gate 5.",
                            Country = "Norway",
                            Name = "Nordic Imports AS"
                        });
                });

            modelBuilder.Entity("Invoicing.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 1,
                            OrderDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 2,
                            OrderDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 3,
                            OrderDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Invoicing.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 3,
                            ProductId = 1,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 3,
                            ProductId = 4,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 3,
                            ProductId = 5,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 4,
                            ProductId = 2,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 4,
                            ProductId = 3,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 4,
                            ProductId = 4,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Invoicing.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDiscountEligible")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFragile")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHazardous")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            IsDiscountEligible = false,
                            IsFragile = true,
                            IsHazardous = false,
                            Name = "Laptop",
                            UnitPrice = 1000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            IsDiscountEligible = true,
                            IsFragile = false,
                            IsHazardous = false,
                            Name = "Mouse",
                            UnitPrice = 20m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Supplies",
                            IsDiscountEligible = false,
                            IsFragile = false,
                            IsHazardous = true,
                            Name = "Battery Pack",
                            UnitPrice = 50m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            IsDiscountEligible = false,
                            IsFragile = true,
                            IsHazardous = false,
                            Name = "Monitor",
                            UnitPrice = 300m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Electronics",
                            IsDiscountEligible = true,
                            IsFragile = false,
                            IsHazardous = false,
                            Name = "Keyboard",
                            UnitPrice = 45m
                        });
                });

            modelBuilder.Entity("Invoicing.Domain.Entities.Order", b =>
                {
                    b.HasOne("Invoicing.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Invoicing.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Invoicing.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Invoicing.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Invoicing.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Invoicing.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Invoicing.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
